name: flutter_json
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^1.4.1
  shake: ^2.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
module:
    androidPackage: com.example.flutter_json
    iosBundleIdentifier: com.example.flutter_json
flutter:
  uses-material-design: true
  assets:
    - assets/liked_songs.json
